name: Qiita Contribution Notifier

on:
  workflow_dispatch: {}
  schedule:
    - cron: '45 * * * *'

jobs:
  check-contribution:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
    steps:
      - name: Restore cache
        id: cache
        uses: actions/cache@v4
        with:
          path: cache
          key: qiita-contribution-${{ github.run_id }}
          restore-keys: |
            qiita-contribution-
      - name: Check Qiita contributions
        run: |
          # 前回の Contribution 数を取得
          PREV_COUNT=0
          if [ -f cache/contribution.txt ]; then
            PREV_COUNT=$(cat cache/contribution.txt)
          fi
          echo "Previous contribution count: $PREV_COUNT"
          
          # Qiita ページから HTML を取得し、Contribution 数を抽出
          HTML=$(curl -s https://qiita.com/zeero)
          CURRENT_COUNT=$(echo "$HTML" | grep 'meta.*content.*Contribution:' | grep -o 'Contribution: [0-9]*' | grep -o '[0-9]*')
          
          # Contribution 数が取得できない場合はエラー
          if [ -z "$CURRENT_COUNT" ]; then
            echo "Error: Could not extract contribution count"
            exit 1
          fi
          
          echo "Current contribution count: $CURRENT_COUNT"
          
          # 差分を計算
          DIFF=$((CURRENT_COUNT - PREV_COUNT))
          echo "Difference: $DIFF"
          
          # 増加があった場合は Slack に投稿
          if [ $DIFF -gt 0 ]; then
            MESSAGE="Contribution数が${DIFF}増加しました"
            curl -X POST https://slack.com/api/chat.postMessage \
              -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"channel\":\"#general\",\"text\":\"$MESSAGE\"}"
            echo "Posted to Slack: $MESSAGE"
          fi
          
          # 現在の Contribution 数をファイルに保存
          echo "$CURRENT_COUNT" > contribution.txt
          echo "Saved current count to file"
      - name: Save result to cache
        run: |
          mkdir -p cache
          if [ -f contribution.txt ]; then
            mv contribution.txt cache/contribution.txt
          fi
