name: Summarize

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title'
        required: false
        default: 'Title'
      message:
        description: 'Message'
        required: true
        default: 'Message'

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Message: ${{ github.event.inputs.message }}"
